// <auto-generated />
namespace PhotoBook.Migrations.PhotoBookContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CommentsModified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommentsModified));
        
        string IMigrationMetadata.Id
        {
            get { return "201701310102313_CommentsModified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
