// <auto-generated />
namespace PhotoBook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PublisherMod1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PublisherMod1));
        
        string IMigrationMetadata.Id
        {
            get { return "201701181917572_PublisherMod1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
